# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e257252d6020fbc924c3e4509074bbfe359cedc71b845188b08d0434fed08a40a972387f827950a872e75e1184dc91458324b1ef1cb621f39bceb43e03fe15

test:
  secret_key_base: 9122ba4a3890faff729240bbfb32f6992601da78bd7c1cb9b35faee1d0bd7ba906012c2deb5e141cc7a386cbf30abb9a335163850bc16ab40e61fbb8d858a455

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
